export const writingPromptDict = {
    'Morning Reflections': [
        'What are the top three goals you want to achieve today?',
        'How do you want to feel by the end of the day?',
        'What is one thing you are looking forward to today?',
        'What is a positive affirmation you can use to start your day?',
        'How will you take care of yourself today?',
        'What tasks are most important for you to complete today?',
        'What mindset do you want to bring to your work or activities today?',
        'How can you make today better than yesterday?',
        'What is one thing you can do today to move closer to your long-term goals?',
        'What are you most excited about today?',
        'How will you stay motivated throughout the day?',
        'What positive impact do you hope to have on others today?',
        'What is one small step you can take towards a personal goal today?',
        'How will you prioritize self-care today?',
        'What is a new habit or practice you want to start today?',
        'What will you do to maintain balance in your life today?',
        'How can you ensure you stay focused and productive today?',
        'What challenges might you face today, and how will you handle them?',
        'How can you make your morning routine more enjoyable?',
        'What is a meaningful intention you want to set for the day?',
        'What’s one thing you can do to bring more joy into your day?',
        'How can you practice mindfulness or presence throughout the day?',
        'What’s one positive change you want to see in your life as a result of today?',
        'How will you end your day in a way that reflects your morning intentions?'
    ],
    'Evening Reflections': [
        'What went well today and what are you proud of?',
        'What challenges did you face today and how did you overcome them?',
        'How did you feel throughout the day, and why?',
        'What did you learn today that you can apply tomorrow?',
        'What is one thing you are grateful for that happened today?',
        'How did you stay true to your goals or intentions today?',
        'What was the highlight of your day?',
        'How can you improve tomorrow based on today’s experiences?',
        'What positive impact did you have on others today?',
        'What is one thing you can do differently tomorrow?',
        'What self-care practices did you use today and how did they benefit you?',
        'What new habit or routine did you try today, and how did it go?',
        'How did you manage stress or challenges today?',
        'What small victories did you experience today?',
        'What did you enjoy most about today?',
        'How did you connect with others today?',
        'What can you do to ensure a restful night’s sleep?',
        'How did today’s experiences shape your overall mood?',
        'What are you looking forward to tomorrow?',
        'What is one thing you want to remember from today?',
        'How did you show kindness or compassion to yourself today?',
        'What can you do before bed to prepare for a successful tomorrow?',
        'How did you maintain balance between work and personal life today?',
        'What lessons did today’s events teach you?'
    ],
    'Gratitude': [
        'Write about something that happened today that you are thankful for.',
        'Describe a person who has positively impacted your life and why you are grateful for them.',
        'List three things you are grateful for today and why.',
        'Write a letter of thanks to someone who has made a difference in your life.',
        'Recall a time when you felt a deep sense of gratitude. Describe the experience.',
        'What small things in life do you appreciate the most? Why?',
        'Write about a recent act of kindness you experienced or witnessed.',
        'Describe a place that brings you comfort and why you are grateful for it.',
        'Think of a challenge you faced recently. How did it help you grow?',
        'Write about a memorable gift you received and how it made you feel.',
        'Describe a hobby or activity that brings you joy and why you are thankful for it.',
        'Reflect on a past failure and how it eventually led to a positive outcome.',
        'Write about a time when you received unexpected help and how it impacted you.',
        'List five things you love about your life right now.',
        'Recall a time when someone’s words of encouragement helped you.',
        'Write about a favorite memory and why it is special to you.',
        'Describe a moment of peace you experienced recently and why you are thankful for it.',
        'Write a thank-you note to someone who has influenced your career or personal growth.',
        'Think of a skill you have developed over time. How has it benefited you?',
        'Describe a time when you felt truly understood by someone.',
        'Write about a recent accomplishment and why you are proud of it.',
        'Think about a time when you overcame fear. How did it change you?',
        'Write about a positive change you made in your life and why it was significant.',
        'Describe a beautiful moment you experienced recently and why it stands out.',
        'Write about a person you admire and why you are grateful for their influence in your life.',
        'Reflect on a time when you felt content and at peace.'
    ],
    'Manifestation': [
        'Write about a goal or dream you are currently manifesting. What steps are you taking to bring it to fruition?',
        'Describe a time when you successfully manifested something you wanted. What strategies did you use?',
        'Visualize your ideal future and write about it in detail. What does it look like, and how can you make it a reality?',
        'Reflect on a limiting belief that might be blocking your ability to manifest your desires. How can you overcome it?',
        'Write about a positive affirmation you can use to support your manifestation goals. How does it resonate with you?',
        'Describe a moment when you felt a strong sense of alignment with your goals. What factors contributed to this feeling?',
        'Write about the role of gratitude in your manifestation process. How does acknowledging what you already have support your goals?',
        'Reflect on any obstacles or challenges you’ve faced while trying to manifest your goals. How did you address them?',
        'Visualize a specific achievement you want to manifest. Write about the emotions and thoughts associated with this achievement.',
        'Consider how your daily actions and mindset support or hinder your manifestation goals. What changes could you make?'
    ],
    'Reflection': [
        'Reflect on a recent challenge and what you learned from it.',
        'Describe a time when you had to make a difficult decision and how you handled it.',
        'Write about a past experience that shaped who you are today.',
        'Think about a personal goal you have achieved. How did it impact you?',
        'Reflect on a recent failure and how it helped you grow.',
        'Write about a significant change you’ve made in your life and how it has affected you.',
        'Describe a time when you felt out of your comfort zone and what you learned from it.',
        'Think about a mentor or role model in your life. How have they influenced you?',
        'Reflect on a recent success. What steps did you take to achieve it?',
        'Write about a time when you had to overcome a fear and how it changed you.',
        'Describe a significant life lesson you’ve learned and how it has impacted your outlook.',
        'Reflect on a moment when you felt truly at peace. What contributed to that feeling?',
        'Write about a time when you had to apologize or seek forgiveness. What did you learn from the experience?',
        'Think about a difficult conversation you had recently. How did it go and what did you learn?',
        'Describe a challenge you’re currently facing and how you plan to overcome it.',
        'Reflect on a time when you helped someone else. How did it make you feel?',
        'Write about a recent personal achievement and what it means to you.',
        'Think about a time when you felt unsupported. How did you handle it?',
        'Describe a significant life change and how it has shaped your perspective.',
        'Reflect on a past relationship and what it taught you about yourself.',
        'Write about a recent mistake and what you learned from it.',
        'Think about a positive habit you’ve developed. How has it impacted your life?',
        'Describe a time when you had to adapt to a new situation. How did it go?',
        'Reflect on a piece of advice you received that changed your perspective.'
    ],
    'Creativity': [
        'Write about a time when you had a burst of creativity and what you created.',
        'Describe a creative project you’ve always wanted to start but haven’t yet.',
        'Write about a challenge you faced in a creative endeavor and how you overcame it.',
        'Think about an artist or creator you admire. How have they influenced your own creativity?',
        'Describe a creative solution you found for a problem you were facing.',
        'Write about a favorite creative activity and what you enjoy most about it.',
        'Reflect on a time when you collaborated on a creative project. How did it go?',
        'Write about a creative block you’ve experienced and how you worked through it.',
        'Describe a recent inspiration that sparked a new idea for you.',
        'Think about a creative risk you took. How did it turn out?',
        'Write about a piece of art or literature that has influenced your creative thinking.',
        'Reflect on a time when you felt particularly creative. What contributed to that feeling?',
        'Write about a creative goal you have and the steps you’re taking to achieve it.',
        'Describe a project or idea you’re passionate about and why it excites you.',
        'Think about a time when you had to think outside the box. What did you come up with?',
        'Write about a mentor or role model in your creative field and how they’ve inspired you.',
        'Describe a time when you combined different ideas or mediums to create something new.',
        'Reflect on a past failure in your creative work and what you learned from it.',
        'Write about a creative routine or habit that helps you stay inspired.',
        'Think about a time when you had to adapt your creative vision. How did you do it?',
        'Describe a recent creative success and what it means to you.',
        'Write about a piece of advice you received about creativity and how it has helped you.',
        'Reflect on a time when you had to balance creativity with practical constraints.',
        'Write about a new skill you’ve learned that has enhanced your creativity.',
        'Describe a time when you collaborated with others to bring a creative idea to life.'
    ],
    'Productivity': [
        'Write about a recent goal you set for yourself and the steps you took to achieve it.',
        'Describe a productivity technique that has helped you stay on track with your tasks.',
        'Reflect on a time when you overcame procrastination. What strategies did you use?',
        'Think about a long-term goal you’re working towards. What motivates you to keep going?',
        'Write about a recent achievement and how it has impacted your overall productivity.',
        'Describe a time when setting clear priorities helped you accomplish more.',
        'Reflect on a past project where you managed your time effectively. What made it successful?',
        'Write about a goal you’ve set for this month and how you plan to achieve it.',
        'Think about a time when you had to balance multiple goals. How did you manage it?',
        'Describe a productivity challenge you faced and how you overcame it.',
        'Write about a daily routine or habit that enhances your productivity.',
        'Reflect on a time when breaking a big goal into smaller tasks made it more achievable.',
        'Describe a productivity tool or app that has been useful for you and why.',
        'Think about a time when you felt particularly productive. What factors contributed to that feeling?',
        'Write about a recent setback in reaching a goal and what you learned from it.',
        'Reflect on a goal-setting technique that has worked well for you in the past.',
        'Describe a time when you adjusted your goals based on changing circumstances.',
        'Write about a recent success in your personal or professional life and how you achieved it.',
        'Think about a goal you’re currently struggling with. What changes can you make to overcome the challenge?',
        'Describe a time when setting specific, measurable goals helped you achieve success.',
        'Reflect on a time when you celebrated a milestone or achievement. How did it impact your motivation?',
        'Write about a strategy you use to stay focused on your goals and avoid distractions.',
        'Describe a time when you collaborated with others to achieve a shared goal. How did it work out?',
        'Think about a personal or professional goal you’d like to set for the future. How will you work towards it?'
    ],
    'Exploring Emotions': [
        'Describe a recent emotional experience and the factors that contributed to it. What did you learn about yourself?',
        'Write about a time when you felt a strong emotion that you didn’t fully understand. How did you process it?',
        'What are the different emotions you experienced this week, and what triggered each of them?',
        'Reflect on how your emotions affect your behavior and relationships. Are there patterns or insights you notice?',
        'Describe an emotion that you find difficult to express. What are some ways you could work on communicating it?',
        'Write about a time when you successfully managed a complex mix of emotions. What strategies helped?',
        'How do you typically cope with overwhelming emotions? What other methods could you try?',
        'Identify a recent emotional reaction that surprised you. What do you think was behind it?',
        'What role do emotions play in your decision-making process, and how do you ensure they don’t override logic?',
        'Write about a time when understanding someone else’s emotions helped you build a stronger connection with them.'
    ],
    'Anxiety': [
        'What are the top three sources of anxiety in your life right now, and what small steps can you take to address them?',
        'Reflect on a recent situation that caused you anxiety. What coping strategies did you use, and how effective were they?',
        'Write about a time when you successfully managed your anxiety. What techniques or approaches helped you?',
        'Describe a specific fear or worry you have. What is the worst-case scenario, and how likely is it to happen?',
        'What are some self-care activities that help you feel more grounded when you are anxious?',
        'Identify a trigger for your anxiety and brainstorm ways to reduce or manage this trigger.',
        'How does your anxiety impact your daily life, and what changes can you make to mitigate its effects?',
        'Write about a recent moment when you felt anxious. What physical sensations did you experience, and how did you respond?',
        'What positive affirmations or mantras can you use to counteract anxiety when it arises?',
        'Reflect on someone you trust and how they support you during anxious times. What makes their support effective?'
    ],
    'Depression': [
        'Describe a time when you felt a sense of accomplishment, no matter how small. How did it impact your mood?',
        'Write about a recent positive interaction or experience that brought you some joy. How did it affect your outlook?',
        'Reflect on a self-care activity or routine that has helped you feel better during a tough time. Why was it effective?',
        'Identify one thing you are grateful for today, and explore how focusing on this gratitude affects your mood.',
        'What are some activities or hobbies that you used to enjoy but have neglected? How can you reintroduce them into your life?',
        'Describe a time when you felt supported by others. What made you feel cared for and understood?',
        'What are some small, achievable goals you can set for yourself to create a sense of purpose and accomplishment?',
        'Reflect on a time when you successfully navigated a low period. What strategies or support systems helped you?',
        'Write about a comforting routine or ritual that brings you peace during challenging times.',
        'How can you incorporate positive self-talk into your daily routine to counteract negative thoughts?'
    ],
    'Fear': [
        'Write about a recent fear you faced and how you confronted it.',
        'Describe a time when you overcame a fear and the impact it had on your life.',
        'Reflect on a fear that has been holding you back. What steps can you take to address it?',
        'Think about a time when facing a fear led to personal growth. What did you learn?',
        'Write about a fear you have about the future and how you plan to manage it.',
        'Describe a time when someone’s support helped you overcome a fear.',
        'Reflect on a recent experience where you felt afraid but chose to take action anyway.',
        'Think about a fear you’ve had since childhood. How has it influenced your life?',
        'Write about a fear that you’re currently working to overcome. What strategies are you using?',
        'Describe a situation where you confronted a fear and what the outcome was.',
        'Reflect on a time when you felt paralyzed by fear. How did you move past it?',
        'Write about a fear that you’ve successfully managed in the past. What helped you?',
        'Think about a fear you would like to confront. What support or resources might you need?',
        'Describe a time when facing a fear helped you gain a new perspective.',
        'Reflect on a fear that you believe is irrational. How can you challenge or change this fear?',
        'Write about a fear that is impacting your daily life and how you’re addressing it.',
        'Describe a time when you helped someone else face their fear. What was the result?',
        'Think about a fear related to a specific goal. How can you work to overcome it?',
        'Write about a fear you have about trying something new and how you might approach it.',
        'Reflect on how your fears have shaped your decisions. Are there any patterns you notice?',
        'Describe a time when a fear you had turned out to be less daunting than you expected.',
        'Write about a fear that you have not yet faced and what might help you take that step.',
        'Think about a personal growth opportunity that involves confronting a fear. How will you approach it?',
        'Describe how facing a fear has affected your confidence and self-perception.'
    ],
    'Anger': [
        'Reflect on a recent situation where you felt angry. What triggered the anger, and how did you respond?',
        'Write about a time when you managed to control your anger effectively. What strategies did you use?',
        'Describe how you typically experience anger. Are there physical or emotional signs that you notice?',
        'What are some constructive ways to express anger without damaging relationships or situations?',
        'Identify a recurring source of anger in your life. What changes can you make to address or reduce this source?',
        'Write about a time when you felt misunderstood while angry. How did you resolve the misunderstanding?',
        'How do you distinguish between anger and other emotions like frustration or disappointment?',
        'What are some healthy outlets or activities that help you manage or release anger?',
        'Reflect on a situation where anger was justified. How did you navigate the situation effectively?',
        'What role does forgiveness play in managing your anger, and how can you practice it more effectively?'
    ],
};