/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function DirtBlock(props) {
    const { nodes, materials } = useGLTF('/models/dirtblock.glb')

    return (
        <group {...props} dispose={null}>
            <mesh castShadow receiveShadow geometry={nodes.Cube_1.geometry} material={materials.grass} />
            <mesh castShadow receiveShadow geometry={nodes.Cube_2.geometry} material={materials.dirt} />
        </group>
    )
}

useGLTF.preload('/models/dirtblock.glb')
